/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package onlineshopping;

/**
 *
 * @author hp
 */

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author chandrasekar
 */
public class Clothing extends javax.swing.JFrame {
    int entry=-1;
    //Cart cart=new Cart();
  test obj=new test();
    class test extends Cart{
      void addToCart(String name,double cost,int stock)
      {
       super.addTo(name,cost,stock);
      }  
      void showCart()
      {
          super.showc();
      }
   }
    public void open()
    {
        setVisible(true);
    }
 
    
    
   public void makeTable(int ch)
    {
        switch (ch)
        {
            case 1:{
                Object[] Data = {"shirt",500.00,0};
            
                Object[] Data1 = {"pant",800.00,10};

                DefaultTableModel model= (DefaultTableModel) t1.getModel();

                Object[] row={Data[0],Data[1],Data[2]};
                Object[] row1={Data1[0],Data1[1],Data1[2]};
                model.setRowCount(0);
                model.addRow(row);
                model.addRow(row1);
                break;
                    }
             case 2:{
                Object[] Data = {"Phone",50000.00,100};
            
                Object[] Data1 = {"Smart Watch",8000.00,10};

                DefaultTableModel model= (DefaultTableModel) t1.getModel();

                Object[] row={Data[0],Data[1],Data[2]};
                Object[] row1={Data1[0],Data1[1],Data1[2]};
                model.setRowCount(0);
                model.addRow(row);
                model.addRow(row1);
                break;
                    }
             case 3:{
                Object[] Data = {"Bag",6000.00,100};
            
                Object[] Data1 = {"Shoe",900.00,10};

                DefaultTableModel model= (DefaultTableModel) t1.getModel();

                Object[] row={Data[0],Data[1],Data[2]};
                Object[] row1={Data1[0],Data1[1],Data1[2]};
                model.setRowCount(0);
                model.addRow(row);
                model.addRow(row1);
                break;
                    }
            case 4 :
            {
                
                Object[] Data = {"Harry Potter 1",500.00,0};
                Object[] Data1 = {"LOTR 1",800.00,10};
                DefaultTableModel model= (DefaultTableModel) t1.getModel();
                model.setRowCount(0);
                Object[] row={Data[0],Data[1],Data[2]};
                Object[] row1={Data1[0],Data1[1],Data1[2]};
                model.addRow(row);
                model.addRow(row1);
                break;
            }
            default:
                JOptionPane.showMessageDialog(this,"Choose a right category !");
        }

    }
       
    public void shows(int ch)
    {
        makeTable(ch);
 DefaultTableModel model=(DefaultTableModel) t1.getModel();
 int i;
 for(i=0;i<model.getRowCount();i++)
 {
 int count=(int)model.getValueAt(i,2);
  if(count>0)
 {
     t1.setValueAt("Available",i,3);
 }
 else
     t1.setValueAt("UnAvailable",i, 3);
 }
    }
   
    public void check(){
         DefaultTableModel model=(DefaultTableModel) t1.getModel();
 int i;
 for(i=0;i<model.getRowCount();i++)
 {
 int count=(int)model.getValueAt(i,2);
  if(count>0)
 {
     t1.setValueAt("Available",i,3);
 }
 else
     t1.setValueAt("UnAvailable",i, 3);
 }
    }
  
    
    
    
    
    public void subtract(String name,int taken)
    {
        makeTable(1);
        DefaultTableModel model = (DefaultTableModel) t1.getModel();
        for(int i =0;i<model.getRowCount();i++)
        {
            if(((String)model.getValueAt(i,0)).equals(name))
            {
                model.setValueAt(((int)model.getValueAt(i,2)-taken), i, 2);
            }
        }
    }
            
    
   
        
        
    
    /**
     * Creates new form Clothing
     */
    public Clothing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cb2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        t1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name ", "Cost ", "Items in Stock", "Available"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(t1);

        jButton1.setText("Add To Cart ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Show Cart");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select another category", "Clothing", "Electronics", "Accessories", "Books" }));
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(75, 75, 75))))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         

        DefaultTableModel model = (DefaultTableModel) t1.getModel();
        int row=t1.getSelectedRow();
        if((int)model.getValueAt(row,2)>0)
        {
String name=(String)model.getValueAt(row,0);
double cost =(Double) model.getValueAt(row,1);
int stock=(int)model.getValueAt(row,2);
obj.addToCart(name,cost,stock);

        }
        else 
            JOptionPane.showMessageDialog(this,"We currently do not have that item in stock ");

// TODO add your handling code here:
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
     obj.showCart();
    
        // TODO add your handling code here:
    }                                        

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {                                    
   int ch=cb2.getSelectedIndex();
              makeTable(ch);
 DefaultTableModel model=(DefaultTableModel) t1.getModel();
 int i;
 for(i=0;i<model.getRowCount();i++)
 {
 int count=(int)model.getValueAt(i,2);
  if(count>0)
 {
     t1.setValueAt("Available",i,3);
 }
 else
     t1.setValueAt("UnAvailable",i, 3);
 }    // TODO add your handling code here:
    }                                   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clothing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clothing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clothing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clothing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clothing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t1;
    // End of variables declaration                   
}

